---
  environment: development
  address: 0.0.0.0
  port: 9100
  pid: local/thin.pid
  rackup: conf/thin.ru
  log: log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 1024
  daemonize: true
  servers: 1
